# -*- coding: utf-8 -*-
"""K-Means Clustering Algorithm _Angel Metanosa Afinda_1301174639.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXQwZ8GJlz4mAE-VpWvJ84gn7DA5lRQd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame ({
     'a' : [12, 14, 19, 22, 11, 9, 25, 28, 30, 7, 10, 24, 27, 29, 33, 23, 16, 13, 26, 31],
     'b' : [21, 41, 91, 22, 12, 8, 52, 82, 32, 5, 4, 42, 72, 92, 34, 37, 61, 62, 44, 55 ]
 })

np.random.seed(100)
k = 3
#centroid[i] = [x,y]
centroids = {
    i+1 : [np.random.randint(0, 100), np.random.randint(0, 100)]
    for i in range (k)
}

fig = plt.figure(figsize = (5, 5))
plt.scatter(df['a'], df['b'], color = 'k')
colmap = {1: 'r', 2: 'g', 3:'b'}
for i in centroids.keys():
  plt.scatter(*centroids[i], color = colmap[i])
plt.xlim(0, 100)
plt.ylim(0, 100)
plt.show()



